version: '3.8'

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - '27017:27017'
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "apt-get update && apt-get install -y curl && curl -f http://localhost:27017 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


  # Interfaz de MongoDB con Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mynetwork
    environment:
      DB_URL: mongodb://admin:password@mongodb:27017/BookReviewDB?authSource=admin  # URL de conexión a MongoDB

  # Frontend (Svelte)
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '8080:80'
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
